
name: ShortcutVisualizer Release

on:
  push:

    tags:
      - v*
    
jobs:

  build:
    
    runs-on: ubuntu-latest

    env:
      Solution_Name: ShortcutVisualizer.sln
      Test_Project_Path: ShortcutVisualizer\ShortcutVisualizer.csproj
      ReleaseZipName: ShortcutVisualizer.zip


    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x


    # Add  MSBuild to the PATH
    # - name: Setup MSBuild.exe
    #   uses: microsoft/setup-msbuild@v2


    # Execute all unit tests in the solution
    - name: Install dependencies
      run: dotnet restore


    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      # run: msbuild $env:Solution_Name /t:Build /p:Configuration=release
      run: dotnet publish -c Release -r win-x64 --framework net6.0-windows --sc false --no-build
 
 
    - name: Zip the Build
      # run: |
      #   $sourceFolder = "${{ github.workspace }}\Hugo\bin\Release\net6.0-windows\win-x64"
      #   $zipFilePath = "${{ github.workspace }}\ShortcutVisualizer.zip"
      #   Compress-Archive -Path $sourceFolder -DestinationPath $zipFilePath -Force
      # shell: pwsh 
      run: zip -rj ShortcutVisualizer.zip ./ShortcutVisualizer/bin/Release/net6.0-windows/win-x64/publish
      
      
    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: 船新版本！
        makelatest: true
        draft: false
        prerelease: false
        files: |
          ShortcutVisualizer.zip
